import cyberlogo from '../Component/Assets/img/cyber.jpg'
import '../Component/Assets/css/BlockPage.css'

function BlockPage() {

    const date= new Date().toLocaleDateString(); 
        return ( <> <div className="BlockpageDiv">
        <div className="BlockpagetopDiv"></div>
        <div className='BlockpagebodyDiv'>
            <h1>Your access to this site has been limited by the site owner</h1>
            <p>Your access to this service has been limited. (HTTP response code 503)</p>
            <p>If you think you have been blocked in error, contact the owner of this site
                for assistance.</p>
            <hr className='hr'/>
            <p className='p'>If you are a WordPress user with administrative privileges on this site,
                please enter your email address in the box below and click "Send". You will then
                receive an email that helps you regain access.</p>
            <form>
                <input type="email" placeholder='email@example.com'></input>
                <button type='submit'>Send Unlock email</button>
            </form>
            <h2>Block Technical Data</h2>
            <table>
            <tr className='the'>
                <th>Block Reason:</th>
                <th>Access from your area has been temporarily limited for security reasons.</th>
            </tr>
            <tr>
                <td>Time:</td>
                <td>{date}</td>
            </tr>
            </table>
            <div className='BlockpagebottomDiv'>
                <img src={cyberlogo} alt="img" width={"160px"} height={"160px"} style={{float:"left"}}/>
                <p>About Wordfence<br/>
                    Wordfence is a security plugin installed on over 4 million WordPress sites. The owner of this site is using Wordfence to manage access to their site.
                    <br/>
                    You can also read the documentation to learn about Wordfence's blocking tools, or visit wordfence.com to learn more about Wordfence.</p>
            </div>
            <p className='p'>Click here to learn more: <a href='https://www.wordfence.com/help/blocking/troubleshooting/#what-is-wordfence'>Documentation</a> </p>
            <div className='BlockpagefooterDiv'><i>
            <p>Generated by Wordfence at {date} </p>
            <p>Your computer's time:{date} </p> </i>
            </div>
         
        </div>
    </div> </>);
}

export default BlockPage;